- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDDFKXMIafzQFacLs0RyQoeTvjFrtR4R2FIlOsvQXOfg ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd # questo chiama nella cartella handlers il task appropriato per gestire l'evento
  # in questo caso faccio dei cambiamenti al config di ssh => restarto il servizio ssh chiamando il task

# esempio per registrare una variabile

- name: Check Ansible version
  command: ansible --version
  register: ansibleVersion # register assegna a una variabile con nome a destra il valore dell'output del modulo ansible

# qua possiamo stampare per esempio l'stdout della variabile
- name: Print version
  debug: # modulo per stampare
    msg: "Ansible Version: {{ ansibleVersion.stdout }}"

