Vagrant.configure("2") do |config|
  config.vm.box = "davidedigiovanni/centos9-arm"
    config.vm.provider 'vmware_fusion' do |provider|
    provider.gui = true
    provider.vmx['memsize'] = '2048'
    provider.vmx['numvcpus'] = '2' 
  end
end